# Generated by Django 5.1.7 on 2025-03-10 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100) manually set by admin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='main.courselevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_level')},
            },
        ),
    ]
